name:                mila
version:             0.1.0.0
github:              "SoptikHa2/mila-compiler"
license:             BSD3
author:              "Petr Šťastný"
maintainer:          "stastpe8@fit.cvut.cz"
copyright:           "2022 Petr Šťastný"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/SoptikHa2/mila-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1 && < 4
- llvm-hs >= 9.0.0 && < 9.1
- llvm-hs-pure >= 9.0.0 && < 9.1

library:
  source-dirs: src

executables:
  mila-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mila

      #tests:
      #  mila-test:
      #    main:                Spec.hs
      #    source-dirs:         test
      #    ghc-options:
      #    - -threaded
      #    - -rtsopts
      #    - -with-rtsopts=-N
      #    dependencies:
      #    - mila
